import type { CookiePartitionKey, ExportFormat, ExportResult, ExportScope, LosslessExportV1, SerializableCookie } from "./types";

const REDACTED_VALUE = "***REDACTED***";

export function toSerializableCookie(cookie: chrome.cookies.Cookie): SerializableCookie {
  return {
    name: cookie.name,
    value: cookie.value,
    domain: cookie.domain,
    hostOnly: cookie.hostOnly,
    path: cookie.path,
    secure: cookie.secure,
    httpOnly: cookie.httpOnly,
    sameSite: cookie.sameSite,
    session: cookie.session,
    expirationDate: cookie.expirationDate,
    storeId: cookie.storeId,
    partitionKey: cookie.partitionKey ? ({ ...cookie.partitionKey } as CookiePartitionKey) : undefined
  };
}

export function createLosslessExport(
  cookies: SerializableCookie[],
  scope: ExportScope,
  redacted = false,
  exportedAt = new Date().toISOString()
): LosslessExportV1 {
  const outputCookies = redacted
    ? cookies.map((cookie) => ({ ...cookie, value: REDACTED_VALUE }))
    : cookies.map((cookie) => ({ ...cookie }));

  return {
    format: "local-cookie-manager-v1",
    exportedAt,
    sourceUrl: scope.url,
    scope,
    redacted,
    cookieCount: outputCookies.length,
    cookies: outputCookies
  };
}

export function formatExport(
  format: ExportFormat,
  cookies: SerializableCookie[],
  scope: ExportScope,
  exportedAt = new Date().toISOString()
): ExportResult {
  const timestamp = exportedAt.replace(/[:.]/g, "-");
  const safeOrigin = scope.origin.replace(/^https?:\/\//, "").replace(/[^a-z0-9.-]+/gi, "_");

  switch (format) {
    case "lossless-json":
      return {
        content: `${JSON.stringify(createLosslessExport(cookies, scope, false, exportedAt), null, 2)}\n`,
        filename: `cookies-${safeOrigin}-${timestamp}.json`,
        mimeType: "application/json",
        containsRealValues: true
      };
    case "redacted-json":
      return {
        content: `${JSON.stringify(createLosslessExport(cookies, scope, true, exportedAt), null, 2)}\n`,
        filename: `cookies-${safeOrigin}-redacted-${timestamp}.json`,
        mimeType: "application/json",
        containsRealValues: false
      };
    case "netscape":
      return {
        content: formatNetscapeCookies(cookies),
        filename: `cookies-${safeOrigin}-${timestamp}.txt`,
        mimeType: "text/plain",
        containsRealValues: true
      };
    case "cookie-header":
      return {
        content: formatCookieHeader(cookies),
        filename: `cookie-header-${safeOrigin}-${timestamp}.txt`,
        mimeType: "text/plain",
        containsRealValues: true
      };
    case "set-cookie":
      return {
        content: formatSetCookieLines(cookies),
        filename: `set-cookie-${safeOrigin}-${timestamp}.txt`,
        mimeType: "text/plain",
        containsRealValues: true
      };
    case "csv":
      return {
        content: formatCsv(cookies),
        filename: `cookies-${safeOrigin}-${timestamp}.csv`,
        mimeType: "text/csv",
        containsRealValues: true
      };
  }
}

export function formatNetscapeCookies(cookies: SerializableCookie[]): string {
  const header = [
    "# Netscape HTTP Cookie File",
    "# Generated by Local Cookie Manager. Keep this file private.",
    ""
  ].join("\n");

  const rows = cookies.map((cookie) => {
    const domain = `${cookie.httpOnly ? "#HttpOnly_" : ""}${cookie.domain}`;
    const includeSubdomains = cookie.hostOnly ? "FALSE" : "TRUE";
    const secure = cookie.secure ? "TRUE" : "FALSE";
    const expires = cookie.session || typeof cookie.expirationDate !== "number" ? "0" : String(Math.trunc(cookie.expirationDate));
    return [
      domain,
      includeSubdomains,
      cookie.path || "/",
      secure,
      expires,
      encodeNetscapeField(cookie.name),
      encodeNetscapeField(cookie.value)
    ].join("\t");
  });

  return `${header}${rows.join("\n")}${rows.length > 0 ? "\n" : ""}`;
}

function encodeNetscapeField(value: string): string {
  return /[\t\r\n]/.test(value) ? encodeURIComponent(value) : value;
}

export function formatCookieHeader(cookies: SerializableCookie[]): string {
  const pairs = cookies.map((cookie) => `${encodeCookieHeaderPart(cookie.name)}=${encodeCookieHeaderPart(cookie.value)}`);
  return `Cookie: ${pairs.join("; ")}\n`;
}

export function encodeCookieHeaderPart(value: string): string {
  if (value === "") {
    return "";
  }

  const safeCookieOctets = /^[!#$%&'()*+\-./0-9:<=>?@A-Z[\]^_`a-z{|}~]+$/;
  return safeCookieOctets.test(value) ? value : encodeURIComponent(value);
}

export function formatSetCookieLines(cookies: SerializableCookie[]): string {
  return `${cookies.map(formatSetCookieLine).join("\n")}${cookies.length > 0 ? "\n" : ""}`;
}

export function formatSetCookieLine(cookie: SerializableCookie): string {
  const parts = [`Set-Cookie: ${encodeCookieHeaderPart(cookie.name)}=${encodeCookieHeaderPart(cookie.value)}`];

  if (!cookie.hostOnly && cookie.domain) {
    parts.push(`Domain=${cookie.domain}`);
  }

  if (cookie.path) {
    parts.push(`Path=${cookie.path}`);
  }

  if (cookie.secure) {
    parts.push("Secure");
  }

  if (cookie.httpOnly) {
    parts.push("HttpOnly");
  }

  const sameSite = formatSameSite(cookie.sameSite);
  if (sameSite) {
    parts.push(`SameSite=${sameSite}`);
  }

  if (!cookie.session && typeof cookie.expirationDate === "number") {
    parts.push(`Expires=${new Date(cookie.expirationDate * 1000).toUTCString()}`);
  }

  return parts.join("; ");
}

export function formatCsv(cookies: SerializableCookie[]): string {
  const header = [
    "name",
    "value",
    "domain",
    "hostOnly",
    "path",
    "secure",
    "httpOnly",
    "sameSite",
    "session",
    "expirationDate",
    "storeId",
    "partitionKey"
  ];

  const rows = cookies.map((cookie) => [
    cookie.name,
    cookie.value,
    cookie.domain,
    String(cookie.hostOnly),
    cookie.path,
    String(cookie.secure),
    String(cookie.httpOnly),
    cookie.sameSite,
    String(cookie.session),
    typeof cookie.expirationDate === "number" ? String(cookie.expirationDate) : "",
    cookie.storeId,
    cookie.partitionKey ? JSON.stringify(cookie.partitionKey) : ""
  ]);

  return `${[header, ...rows].map((row) => row.map(csvCell).join(",")).join("\n")}\n`;
}

function csvCell(value: string): string {
  if (/[",\r\n]/.test(value)) {
    return `"${value.replace(/"/g, '""')}"`;
  }
  return value;
}

function formatSameSite(sameSite: SerializableCookie["sameSite"]): string | undefined {
  if (sameSite === "no_restriction") {
    return "None";
  }
  if (sameSite === "lax") {
    return "Lax";
  }
  if (sameSite === "strict") {
    return "Strict";
  }
  return undefined;
}
